name: 'Gimlet Artifact Shipper Action'
author: 'Gimlet.io'
description: 'Ship releasable software artifacts to Gimlet'
inputs:
  fields:
    description: 'Metadata to attach to the artifact'
    required: false
  debug:
    description: 'Set it to true if you want to print the artifact instead of shipping it'
    required: false
    default: "false"
  branchHead:
    description: "Branch commit sha for PRs. $GITHUB_SHA contains the merge head sha for PRs, which is a sha that Gimlet doesn't know about"
    default: ${{ github.event.pull_request.head.sha }}
    required: false
  watch:
    description: 'Set it to true if you want to watch tracking the artifact'
    required: false
    default: "false"
  timeout:
    description: 'Set the time for wait flag of artifact track'
    required: false
    default: "10m"
outputs:
  artifact-id:
    description: 'ID of the created artifact'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fields }}
    - ${{ inputs.debug }}
    - ${{ inputs.watch }}
    - ${{ inputs.timeout }}
branding:
  icon: arrow-right
  color: yellow
